name: Build

on:
  workflow_run:
    workflows: [ test ]
    types: [ completed ]
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: cinema:latest
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Image
        uses: addnab/docker-run-action@v3
        with:
          image: cinema:latest
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: |
            pnpm build
            npm publish
            
            
          
